# Generated by Django 6.0.2 on 2026-04-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='cooldown',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('M', 'Monthly'), ('W', 'Weekly')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_rarity',
            field=models.IntegerField(choices=[(2, 'Epic'), (0, 'Common'), (3, 'Legendary'), (1, 'Rare')], default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_state',
            field=models.IntegerField(choices=[(1, 'Revealed'), (2, 'Active'), (0, 'Hidden'), (3, 'Finished')], default=2),
        ),
        migrations.AlterField(
            model_name='tree',
            name='area',
            field=models.IntegerField(choices=[(1, 'Fitness'), (4, 'Custom'), (2, 'Language'), (3, 'Creativity'), (0, 'Reading')], default=4),
        ),
    ]
