# Generated by Django 6.0.2 on 2026-05-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='cooldown',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_rarity',
            field=models.IntegerField(choices=[(0, 'Common'), (1, 'Rare'), (2, 'Epic'), (3, 'Legendary')], default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_state',
            field=models.IntegerField(choices=[(0, 'Hidden'), (1, 'Revealed'), (2, 'Active'), (3, 'Finished')], default=2),
        ),
        migrations.AlterField(
            model_name='tree',
            name='area',
            field=models.IntegerField(choices=[(0, 'Reading'), (1, 'Fitness'), (2, 'Language'), (3, 'Creativity'), (4, 'Custom')], default=4),
        ),
    ]
