# Generated by Django 6.0.2 on 2026-05-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltree', '0002_alter_node_cooldown_alter_node_node_rarity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='cooldown',
            field=models.CharField(blank=True, choices=[('W', 'Weekly'), ('M', 'Monthly'), ('D', 'Daily')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_rarity',
            field=models.IntegerField(choices=[(1, 'Rare'), (3, 'Legendary'), (0, 'Common'), (2, 'Epic')], default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_state',
            field=models.IntegerField(choices=[(2, 'Active'), (3, 'Finished'), (1, 'Revealed'), (0, 'Hidden')], default=2),
        ),
        migrations.AlterField(
            model_name='tree',
            name='area',
            field=models.IntegerField(choices=[(3, 'Creativity'), (1, 'Fitness'), (2, 'Language'), (0, 'Reading'), (4, 'Custom')], default=4),
        ),
    ]
